### PR TITLE
Add a new Pull Request Template [ issue#1 ]

### PR DESCRIPTION
**Pull request by nov0ax**
### 📝 Sumary
Closes <a href="https://github.com/Crypto-Jaguars/Revolutionary_Farmers/issues/1"> Add template for Pull Request #1</a>

### 🔄 Changes made:
Create a .github directory. 
Create a PULL-REQUEST_TEMPLATE.md file

This is a quick preview of the final template
image

### CODE REVIEW

**Review by sasasamaes — APPROVED** [review]
Nice Work @nov0ax 🫡

**Review by ManuelJG1999 — APPROVED** [review]
nicely done, Diana!

**Review by salazarsebas — APPROVED** [review]
Good job, congrats @nov0ax . ⛩️

**Comment by nov0ax** [comment]
Thank you all, good luck with this amazing project, can´t wait to continue contributing with you all.

**Pull request merged**
