### PR TITLE
Add an Issue Template to the Repository

### LINKED ISSUE #5: Add an Issue Template to the Repository
## Create a standardized template to guide contributors in creating well-structured and detailed issues.

**The template should include:**

	•	Title: A concise and descriptive title for the issue.
	•	Description: A clear explanation of the issue or feature request.
	•	Steps to Reproduce (for bugs): A list of steps to replicate the issue.
	•	Expected Behavior: What should happen if the issue is resolved.
	•	Screenshots or Logs: Space for attaching relevant images or logs.
	•	Environment Details: Information such as OS, browser, or software versions.
	•	Additional Context: Any other details that might help resolve the issue.

**The template file should be named ISSUE_TEMPLATE.md and placed in the .github folder.**

### PR DESCRIPTION
**Pull request by josephpdf**
### 📝 Summary 
- Closes #5 
### 🔄 Changes Made
- Creation of the .github folder
- Creating the ISSUE_TEMPLATE.md

### CODE REVIEW

**Review by sasasamaes — APPROVED** [review]
Nice Work @josephpdf 🫡

**Comment by josephpdf** [comment]
> Nice Work @josephpdf 🫡

This is how the template look like:

**Review by salazarsebas — APPROVED** [review]
Good work, congrats @josephpdf ! 🫡

**Review by ManuelJG1999 — APPROVED** [review]
looks nice. 
Thank you @josephpdf

**Pull request merged**
