### PR TITLE
Setup jest libray

### LINKED ISSUE #27: Implement Jest or Testing Libraries
**Objective**
Implement a robust testing framework to improve the quality and reliability of the code.
Steps to Implement Jest

1. **Installation**

`npm install --save-dev jest @types/jest ts-jest`

2. **Configuration**

 1. Create File jest.config.js
 2. Configure scripts in package.json:
 `"scripts": {
   "test": "jest",
   "test:watch": "jest --watch"
 }`

3 **Test Structure**
- Create Directory /tests
- Name test files with the format [ComponentName].test.ts

4. **Examples of Test Types*
- Unit tests
- Integration tests
- Snapshot tests
- Dependency Mocking

 **Recommended Additional Libraries**
- @testing-library/react for component testing
- jest-dom for personalized assertions

**Acceptance Criteria**
- [ ] Jest configured correctly
- [ ]  At least 70% code coverage
- [ ]  Tests for main components
- [ ]  CI configuration to run tests

**Notes**
Consult official Jest documentation for advanced configuration details.

### PR DESCRIPTION
**Pull request by Benjtalkshow**
# Pull Request Overview

## 📝 Summary
Provide a brief summary of what this PR accomplishes.

### 🪧 Related Issues
- Closes #27  Replace with actual issue number.

### 🏁 Type of Change
Mark with an `x` all the checkboxes that apply (like `[x]`).

- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

### 🔄 Changes Made
Provide a clear and concise description of what you changed and why.

### 🚀 Implementation Details
Describe how you implemented the changes.

### 🛠 Technical Notes
Include any technical details that reviewers should be aware of.

### ✅ Tests Results
Describe the tests you performed to verify your changes:

### Test Coverage
- [ ] ✅ Unit Tests
- [ ] ✅ Integration Tests
- [ ] ✅ Manual Testing

### 📸 Evidence
Provide relevant evidence of testing (screenshots, test outputs, etc.).

### 🔍 Testing Notes
Include any special testing considerations or edge cases checked.

### 🔜 Next Steps
Indicate actions or improvements to be taken after this PR, if applicable.

## Release Notes

- **New Features**
	- Introduced a comprehensive testing guide in the README, enhancing usability.
	- Added a new GitHub Actions workflow for automated testing and build processes.
	- New Jest and Cypress configuration files to streamline testing.
	- Implemented a new test suite for the Header component.

- **Documentation**
	- Updated README with a section on testing procedures.
	- Created a detailed `TEST.md` for frontend testing instructions.

- **Bug Fixes**
	- Improved linting and formatting checks in the build process.

- **Chores**
	- Updated `package.json` with new scripts and dependencies for testing.
	- Enhanced TypeScript configuration for better test file recognition.

### CODE REVIEW

**Review by sasasamaes — APPROVED** [review]
Nice work @Benjtalkshow 🚀🫡

**Comment by Benjtalkshow** [comment]
> Nice work @Benjtalkshow 🚀🫡

Will update it soon

**Comment by Benjtalkshow** [comment]
- [x] All test configurations working
- [x] E2E testing framework configured
- [x] Coverage reporting set up
- [x] Documentation added
- [x] CI integration ready 
## @sasasamaes The `workflow` folder was renamed to `__workflow__` because i dont have the permission to push a workflow.
Thanks

Everything tested and working
image

**Comment by Benjtalkshow** [comment]
@sasasamaes  @DiegoB1911  Please Review

**Review by DiegoB1911 — APPROVED** [review]

**Comment by DiegoB1911** [comment]
Nice work @Benjtalkshow!

**Pull request merged**
